name: Stories app CI

on:
  push: 
    branches: [ master ]

jobs: 
  deploy: 
    runs-on: ubuntu-latest
    
    steps: 
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Create .env file
        id: env_file
        uses: timheuer/base64-to-file@v1
        with:
          fileName: ".env"
          encodedString: ${{ secrets.ENV }}

      - name: Move .env into project
        run: |
          mv ${{ steps.env_file.outputs.filePath }} .

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          file: ./Dockerfile
          push: false
          tags: eu.gcr.io/stories-fans/app

      - name: Deploy to Cloud Run (Setup)
        uses: google-github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@main
        with:
          image: eu.gcr.io/stories-fans/app
          service: stories-fans
          region: europe-north1

      - name: Use Output
        run: curl "${{ steps.deploy.outputs.url }}"
