name: Stories app CI

on:
  push: 
    branches: [ develop ]

jobs: 
  tests: 
    runs-on: ubuntu-latest

    steps: 
      - name: Checkout
        uses: actions/checkout@master
      
      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependences
        run: npm ci
      
      - name: Run tests
        run: npm run test