name: Stories app CI

on:
  push: 
    branches: [ main ]

jobs: 
  deploy: 
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: eu.gcr.io/${{ secrets.GCP_SERVICE }}/${{ secrets.GCP_APPLICATION }}
    
    steps: 
      - name: Checkout
        uses: actions/checkout@master

      - name: Create .env file
        id: env_file
        uses: timheuer/base64-to-file@v1
        with:
          fileName: ".env"
          encodedString: ${{ secrets.ENV }}

      - name: Move .env into project
        run: mv ${{ steps.env_file.outputs.filePath }} .

      - name: Deploy to Cloud Run (Setup)
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_SERVICE }}
          service_account_email: ${{ secrets.GCP_EMAIL }}
          service_account_key: ${{ secrets.GCP_CREDENTIALS }}
          export_default_credentials: true

      - name: Configure Docker
        run: gcloud auth configure-docker --quiet

      - name: Build docker
        run: docker build . -t $IMAGE_NAME

      - name: Push Docker image
        run: docker push $IMAGE_NAME

      - name: Deploy Docker image
        run: gcloud run deploy ${{ secrets.GCP_PROJECT }} --image=$IMAGE_NAME --region=${{ secrets.GCP_REGION }} --platform managed
